FROM ghcr.io/markusjx/prebuilt-debug-jdk:{{JDK_VERSION}} as jdk
FROM ghcr.io/markusjx/prebuilt-debug-nodejs:{{NODE_VERSION}} as node
FROM debian:{{DEBIAN_VERSION}}-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libclang-dev clang libatomic1 && apt-get install -y curl && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y && \
    PATH="$PATH:/root/.cargo/bin" \
    rustup toolchain install nightly --allow-downgrade --profile default --component clippy && \
    PATH="$PATH:/root/.cargo/bin" \
    rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu && \
    apt-get remove -y curl && apt-get autoremove -y && apt-get clean -y

COPY --from=jdk /jdk /jdk
COPY --from=node /nodejs /nodejs

ENV JAVA_HOME=/jdk
ENV RUSTFLAGS="-Clinker=clang -Zsanitizer=address"
ENV RUSTDOCFLAGS="-Clinker=clang -Zsanitizer=address"
ENV ASAN_OPTIONS="detect_leaks=0"
ENV RUST_BACKTRACE=1
ENV FORCE_RUN_ALL_TESTS=true
ENV INCREASE_TIMEOUT=true
#ENV SKIP_CLASS_TEST=true
ENV CI=true
ENV PATH="$PATH:/root/.cargo/bin:/jdk/bin:/nodejs/node:/nodejs/npm"

WORKDIR /app
CMD [ "/bin/bash" ]