/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_markusjx_bridge_JavaFunctionCaller */

#ifndef _Included_io_github_markusjx_bridge_JavaFunctionCaller
#define _Included_io_github_markusjx_bridge_JavaFunctionCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_markusjx_bridge_JavaFunctionCaller
 * Method:    callNodeFunction
 * Signature: (JLjava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_github_markusjx_bridge_JavaFunctionCaller_callNodeFunction(JNIEnv *, jobject, jlong,
                                                                                             jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
