/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_markusjx_bridge_StdoutRedirect_CallbackOutputStream */

#ifndef _Included_io_github_markusjx_bridge_StdoutRedirect_CallbackOutputStream
#define _Included_io_github_markusjx_bridge_StdoutRedirect_CallbackOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_markusjx_bridge_StdoutRedirect_CallbackOutputStream
 * Method:    writeLine
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_io_github_markusjx_bridge_StdoutRedirect_00024CallbackOutputStream_writeLine
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
