FROM node:{{NODE_VERSION}}-alpine RUN apk update && apk add curl build-base
clang16-libclang wget &&\ wget -O /etc/apk/keys/adoptium.rsa.pub\
https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk
&&\ echo 'https://packages.adoptium.net/artifactory/apk/alpine/main' >>
/etc/apk/repositories &&\ apk add temurin-{{JDK_VERSION}}-jdk &&\ curl --proto
'=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y ENV
PATH="$PATH:/root/.cargo/bin" ENV JAVA_HOME="/usr/lib/jvm/java-{{JDK_VERSION}}-temurin"
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/jvm/java-{{JDK_VERSION}}-temurin/lib/server"
ENTRYPOINT [ "/bin/sh" ]