name: Build alpine build container
on:
    workflow_dispatch:
        inputs:
            node-version:
                description: 'Node version'
                required: true
            jdk-version:
                description: 'JDK version'
                required: true

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: java-bridge-node-alpine-build

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create dockerfile
              uses: edgardleal/mustache-template-action@v1.0.4
              env:
                  JDK_VERSION: ${{github.event.inputs.jdk-version}}
                  NODE_VERSION: ${{github.event.inputs.node-version}}
              with:
                  input: ./docker/Dockerfile-build-alpine.hbs
                  output: Dockerfile
            - name: Build image
              run: docker build . --file Dockerfile --tag $IMAGE_NAME
            - name: Log into registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
            - name: Push latest image
              run: |
                  IMAGE_ID=$REGISTRY/${{ github.repository }}
                  IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')/$IMAGE_NAME
                  docker tag $IMAGE_NAME $IMAGE_ID:node-$NODE_VERSION-jdk-$JDK_VERSION
                  docker push $IMAGE_ID:node-$NODE_VERSION-jdk-$JDK_VERSION
              env:
                  NODE_VERSION: ${{github.event.inputs.node-version}}
                  JDK_VERSION: ${{github.event.inputs.jdk-version}}
