name: Address Sanitizer

on:
    push:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: 18
                  check-latest: true
                  cache: 'npm'
            - name: Setup java 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.2.1
            - name: Cache java definitions
              uses: actions/cache@v3
              with:
                  path: '**/test/javaDefinitions'
                  key: ${{runner.os}}-javaDefinitions

            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Generate test types
              run: npm run generateTestTypes -- -- --system-test
            - name: Remove target and dist directories
              run: |
                  rm -rf dist
                  mv target target.bak
                  cp -r test/javaDefinitions javaDefinitions.bak

            - name: Run tests with address sanitizer
              uses: addnab/docker-run-action@v3
              with:
                  registry: gcr.io
                  image: ghcr.io/markusjx/node-java-bridge/java-bridge-asan-testcontainer:latest
                  options: -v ${{ github.workspace }}:/app
                  run: |
                      npm run build:napi:debug -- --target=x86_64-unknown-linux-gnu \
                        --cargo-flags="-Zbuild-std"
                      npm run build:ts
                      npm run generateTestTypes -- -- --update-imports
                      npm run mocha -- -- --timeout 10000

            - name: Create test summary
              uses: test-summary/action@dist
              if: always()
              with:
                  show: all
                  paths: testResults.xml
            - name: Move target back
              run: |
                  rm -rf target
                  mv target.bak target
                  rm -rf test/javaDefinitions
                  mv javaDefinitions.bak test/javaDefinitions
