name: Address Sanitizer

env:
    DEBUG: 'napi:*'

on:
    push:
    pull_request:

jobs:
    build_and_test:
        name: ubuntu - node@18
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: 18
                  check-latest: true
                  cache: 'npm'

            - name: Setup java 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Install
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  profile: minimal
                  components: rust-src
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.2.1

            - name: Cache java definitions
              uses: actions/cache@v3
              with:
                  path: test/javaDefinitions/**
                  key: ${{ runner.os }}-javaDefinitions-${{ hashFiles('**/test/javaDefinitions/**') }}

            - name: Install dependencies
              run: npm ci

            - name: Build tests
              run: npm run build:debug
              env:
                  RUST_TARGET: x86_64-unknown-linux-gnu
                  RUST_BACKTRACE: 1
                  RUSTFLAGS: -Z sanitizer=address
                  ASAN_OPTIONS: detect_leaks=0

            #- name: Cargo tests with address sanitizer
            #  run: |
            #      LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/9/libasan.so cargo test --verbose --all-features
            #  env:
            #      RUST_TARGET: x86_64-unknown-linux-gnu
            #      RUST_BACKTRACE: 1
            #      RUSTFLAGS: -Z sanitizer=address
            #      ASAN_OPTIONS: detect_leaks=0

            - name: Unit tests with address sanitizer
              run: |
                  LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/9/libasan.so npm run generateTestTypes
                  npm run build:tests
                  LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/9/libasan.so npm run test:asan
              env:
                  RUST_TARGET: x86_64-unknown-linux-gnu
                  RUST_BACKTRACE: 1
                  RUSTFLAGS: -Z sanitizer=address
                  ASAN_OPTIONS: detect_leaks=0
                  FORCE_RUN_ALL_TESTS: true
                  INCREASE_TIMEOUT: true

            - name: Clear the cargo caches
              run: |
                  cargo install cargo-cache --no-default-features --features ci-autoclean
                  cargo-cache
