name: Check-style
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check-ts-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm i -D
            - name: Prettier check
              run: npm run prettier:check

    check-rust-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Check style
              run: cargo fmt -- --check
