name: Test

on:
    push:
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    test-cargo:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.0.0
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose

    test-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: 16.x
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.0.0
            - name: Install
              run: npm ci
            - name: Run tests
              run: npm test

    benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: 16.x
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin' # See 'Supported distributions' for available options
                  java-version: '17'
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.0.0
            - name: Install
              run: npm ci
            - name: Run benchmarks
              run: npm run benchmark
